#!/usr/bin/env sh

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               25
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

# float space 1 and 2 (laptop screen)

yabai -m config --space 1 layout stack
yabai -m config --space 2 layout stack

# mouse config
yabai -m config mouse_drop_action stack
yabai -m config mouse_modifier alt

# Emacs fix
nom_managed-apps='^(Caprine|iTerm|Alfred)$'
yabi -m rule --add app="Emacs" manage=on
yabi -m rule --add app="${non_managed_apps}" manage=off
# yabi -m rule --add app="Caprine" manage=off
# yabi -m rule --add app="iTerm" manage=off
# yabi -m rule --add app="Alfred" manage=off

echo "yabai configuration loaded.."
