#!/usr/bin/env sh

# focus window
alt + shift - j : yabai -m window --focus prev
alt + shift - k : yabai -m window --focus next

hyper - w : yabai -m window --focus north
hyper - a : yabai -m window --focus west
hyper - s : yabai -m window --focus south
hyper - d : yabai -m window --focus east

# swap window in monitor
alt + shift - w : yabai -m window --warp north
alt + shift - a : yabai -m window --warp west
alt + shift - s : yabai -m window --warp south
alt + shift - d : yabai -m window --warp east

# rotate window tree
alt + shift - r : yabai -m space --rotate 90

# move window to monitor and focus
hyper - h : yabai -m window --display next; yabai -m display --focus next
hyper - l : yabai -m window --display prev; yabai -m display --focus prev

# focus monitor
hyper - 1  : yabai -m display --focus 1
hyper - 2  : yabai -m display --focus 2
hyper - 3  : yabai -m display --focus 3

# change layout of desktop
ctrl + alt + shift - f : yabai -m space --layout float
ctrl + alt + shift - b : yabai -m space --layout bsp

# fullscreen window
hyper - f : yabai -m window --toggle zoom-fullscreen

# balance size of windows
hyper - 0 : yabai -m space --balance

# change region size
shift + alt - h : yabai -m window --ratio rel:-0.1
shift + alt - l : yabai -m window --ratio rel:0.1

# Change split type
alt + shift + ctrl - space : yabai -m window --toggle split
