-- https://www.lazyvim.org/plugins/linting
-- return {
--   "mfussenegger/nvim-lint",
--   opts = {
--     linters_by_ft = {
--       markdown = { "markdownlint" },
--     },
--     linters = {
--       markdownlint = {
--         args = {
--           "--disable",
--           "MD005",
--           "MD007",
--           "MD013",
--           "MD026",
--           "MD029",
--           "--",
--         },
--       },
--     },
--   },
-- }
return {}
